services:
  vedirect_mqtt:
    container_name: vedirect_mqtt
    build: <location of vedirect_mqtt.py>/.
    restart: unless-stopped
    environment:
      - LOGLEVEL=DEBUG
      - VEDIRECT_NAME=BMV700
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_ROOT=VEDirectMQTT
      - MQTT_USER=ClassicPublisher
      - MQTT_PASS=ClassicPub123
    networks:
      - iotstack_nw
